# Generated by Django 5.1.1 on 2024-10-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_book_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.CreateModel(
            name='Subgenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgeneros', to='tasks.genre')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='subgenre',
            field=models.ManyToManyField(related_name='books', to='tasks.subgenre'),
        ),
    ]
