# Generated by Django 5.1.1 on 2024-11-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_quiz_response_count_userquizresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
