# Generated by Django 5.1.1 on 2024-11-13 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_userquizresponse_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresponse',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquizresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
